import { Inter } from "next/font/google";
import "./globals.css";
import { Loader, MantineProvider, createTheme } from "@mantine/core";
import { Suspense } from "react";
import NextTopLoader from "nextjs-toploader";
import "@mantine/core/styles.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "VMCO",
  description: "Generated by create next app",
};

const theme = createTheme({
  fontFamily: "Open Sans, sans-serif",
  primaryColor: "orange",
  defaultRadius: "7px",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextTopLoader showSpinner={false} color="#FFBF00" />
        <MantineProvider theme={theme}>
          <Suspense
            fallback={
              <>
                <div className="w-full h-screen grid place-content-center">
                  <Loader className="w-10 h-10" />
                </div>
              </>
            }
          >
            {children}
          </Suspense>
        </MantineProvider>
      </body>
    </html>
  );
}
